import { buildSmartObjectResponseSchema } from "../validation/smartObjectSchema.js";

function formatNeeds(needs) {
  return needs.map((need) => [
    `Need: ${need.name}`,
    `Definition: ${need.definition}`,
    "Weak calibration reference:",
    `- interaction: ${need.weakReference.example}`,
    `- weight: ${need.weakReference.weight}`,
    "Strong calibration reference:",
    `- interaction: ${need.strongReference.example}`,
    `- weight: ${need.strongReference.weight}`
  ].join("\n")).join("\n\n");
}

export function buildSmartObjectPrompt({ locationDescription, needs }) {
  const responseSchema = buildSmartObjectResponseSchema(needs);

  return [
    "You generate JSON for an experimental LLM Smart Object Generator.",
    "",
    "Task:",
    "Generate a concise set of useful physical or environmental objects appropriate for the described location.",
    "For each object, generate one or more meaningful interactions. Each interaction may advertise only the supplied NPC needs it can meaningfully satisfy.",
    "",
    `Location description: ${locationDescription}`,
    "",
    "Allowed needs, definitions, and calibration references:",
    formatNeeds(needs),
    "",
    "Meaning of an interaction and advertisement:",
    "An object is a physical or environmental entity.",
    "An interaction describes one complete way an NPC can use that object, such as sit_and_relax, sleep, watch_television, read_a_book, get_and_drink_coffee, or get_and_eat_food.",
    "Prefer complete need-satisfying interactions over incomplete enabling steps. For example, use get_and_drink_coffee instead of press_button, and read_a_book instead of take_book.",
    "An advertisement means the interaction communicates that performing it can help satisfy a particular NPC need.",
    "The advertisement weight is the base strength with which performing that interaction satisfies the advertised need.",
    "Some interactions are need-satisfying interactions: they are useful because performing them directly helps an allowed NPC need, so they normally contain one or more advertisements.",
    "Some interactions are support, control, or maintenance interactions: they change object-side state or resources so other interactions remain coherent, such as turn_on_tv, turn_off_tv, unlock_door, open_cabinet, clean_toilet, refill_coffee_machine, or repair_machine.",
    "Support, control, and maintenance interactions may use an empty advertisements array when they do not directly satisfy a supplied need.",
    "Never invent tiny or weak advertisements merely to make the advertisements array non-empty. Low weights such as 0.05 still require a genuine need-satisfaction relationship.",
    "Generate support, control, or maintenance interactions only when they are necessary to make declared state or finite resources coherent. Do not decompose every useful interaction into internal button presses or preparation steps.",
    "",
    "Duration model:",
    "Every interaction requires exactly one duration object.",
    "Allowed duration types are instant, fixed, and continuous.",
    "Use instant when the interaction completes almost immediately and does not meaningfully occupy the NPC over simulation time. Instant durations must omit seconds.",
    "Use fixed when the interaction has a natural completion point and takes an approximately predictable amount of time. Fixed durations require plausible real-world seconds greater than 0 and no greater than 86400.",
    "Use continuous when there is no predetermined completion time and a future NPC or utility system may decide when to stop. Continuous durations must omit seconds.",
    "Duration applies to the complete interaction, not one animation or small internal step.",
    "Do not classify every interaction as fixed. Do not classify every interaction as continuous. Use instant only when time is negligible for decision-making.",
    "Duration examples:",
    "- sit_and_relax -> continuous",
    "- sleep -> continuous",
    "- watch_television -> continuous",
    "- get_and_drink_coffee -> fixed, approximately 30-120 seconds",
    "- eat_a_meal -> fixed, approximately 600-1800 seconds",
    "- wash_hands -> fixed, approximately 20-60 seconds",
    "- turn_on_light -> instant",
    "",
    "Object capacity model:",
    "Every generated object requires exactly one capacity object.",
    "Capacity belongs to the object, not to individual interactions.",
    "All interactions on one object share the same capacity pool.",
    "Capacity counts simultaneous users of one generated object instance.",
    "Each generated object entry represents one object instance: chair_01 is one chair, chair_02 is a second chair.",
    "Capacity does not represent the number of object copies. Do not create chair_01 with slots 5 to represent five separate individual chairs.",
    "Use limited capacity when the object has a meaningful finite number of simultaneous users.",
    "Limited capacity requires a plausible integer slots value from 1 to 100.",
    "Use unlimited capacity only when the object does not require meaningful exclusive physical usage slots in this simplified simulation.",
    "Unlimited capacity must omit slots.",
    "Do not use unlimited merely because the exact capacity is uncertain.",
    "Infer capacity from object type, object description, location context, and ordinary real-world usage.",
    "Avoid setting every limited capacity to 1. Avoid unrealistically large capacities.",
    "A multi-person object such as one sofa, bench, table, or vehicle seat bank may legitimately have multiple slots.",
    "Object capacity examples:",
    "- single chair -> limited, slots 1 -> when_capacity_available",
    "- single bed -> limited, slots 1 -> when_capacity_available",
    "- toilet -> limited, slots 1 -> when_capacity_available",
    "- shower -> limited, slots 1 -> when_capacity_available",
    "- three-seat sofa -> limited, slots 3 -> when_capacity_available",
    "- four-person dining table -> limited, slots 4 -> when_capacity_available",
    "- public notice board -> unlimited -> always",
    "- radio -> unlimited -> always",
    "- shared television viewing -> unlimited -> always",
    "",
    "Object-side state and finite resources:",
    "Every object requires stateFlags and resources arrays. These arrays may be empty and often should be empty.",
    "Every interaction requires requirements and effects arrays. These arrays may be empty and often should be empty.",
    "Most passive furniture and static objects should have no state flags, no resources, empty requirements, and empty effects.",
    "Examples that normally need empty state/resource arrays include sofa, chair, bench, table, bookshelf, painting, notice board, and exercise mat.",
    "Use only approved state IDs: powered_on, operational, locked, open, clean.",
    "Do not give every electronic device all possible states without a meaningful reason.",
    "Only model finite object-side stock as resources, such as coffee_servings, snack_units, paper_sheets, soap_uses, water_bottles, clean_towels.",
    "Do not use resources for ordinary mains electricity or piped water unless the location explicitly says supply is limited.",
    "Every declared state must be referenced by at least one requirement on that same object. A set_state effect may reference a declared state, but an effect-only reference does not justify declaring the state.",
    "Do not create a state merely to record aftermath if no interaction will ever check that state as a requirement.",
    "When an interaction changes a reusable object into a blocking or depleted state, include a coherent restoration interaction when appropriate, such as clean_toilet requiring clean false and setting clean true, or turn_off_tv requiring powered_on true and setting powered_on false.",
    "Restoration, control, and refill interactions may use empty advertisements arrays when they are object-side support actions rather than direct need satisfaction.",
    "Do not force a restoration interaction when the state change is intentionally permanent or outside the simplified object model.",
    "Every declared resource must be referenced by at least one requirement or effect on that same object. Refill effects may be the only reference for a replenishment interaction.",
    "Every requirement and effect must reference declarations on the same parent object only.",
    "Requirements must be object-side only. Do not use NPC need urgency, NPC role, NPC personality, NPC age, NPC inventory, NPC money, NPC skill, NPC permission, time of day, schedule, weather, distance, location, pathfinding, occupancy, queues, available capacity, or another object.",
    "Effects are declarative object-side changes expected after successful completion. This generator does not execute them.",
    "Do not put need satisfaction into effects. Need satisfaction belongs only in advertisements.",
    "Do not model capacity through resources, requirements, or effects. Capacity availability remains represented by availability.",
    "Do not model current users, occupancy, queues, reservations, arbitrary Boolean expressions, scripts, or code.",
    "Avoid over-modelling simple objects.",
    "State/resource examples:",
    "- sofa -> no state flags -> no resources -> empty requirements -> empty effects",
    "- notice board -> no state flags -> no resources -> empty requirements -> empty effects",
    "- coffee machine -> powered_on and operational states -> coffee_servings resource -> state/resource requirements -> resource consumption effect",
    "",
    "Capacity-aware availability model:",
    "Every interaction requires exactly one availability object.",
    "Availability describes whether this interaction should currently be visible as a possible choice from the object side.",
    "The only allowed availability types are always and when_capacity_available.",
    "Availability must match object capacity: limited capacity -> when_capacity_available; unlimited capacity -> always.",
    "Do not generate the old when_free availability value.",
    "Do not generate runtime occupancy data such as occupied, is_free, current_users, user_count, available_slots, remaining_slots, claimed_slots, occupant_ids, reserved_by, reservations, queues, or queue positions.",
    "",
    "Need-specific weight calibration:",
    "Calibration references define the approximate low and high ends for each specific need.",
    "Compare each newly generated interaction against both references for that need and assign a proportional value based on relative strength.",
    "Do not simply copy the weak or strong reference value. Values between the references are expected.",
    "A generated interaction may reasonably be weaker than the weak reference or stronger than the strong reference only in exceptional cases.",
    "Never exceed 1.0.",
    "Do not generate a reference object merely because it appears in the calibration context.",
    "The references are examples, not mandatory objects for the location.",
    "Per-need calibration references are more important than the generic global weight bands.",
    "Generic fallback scale:",
    "- 0.01-0.19 = minimal effect",
    "- 0.20-0.39 = weak effect",
    "- 0.40-0.59 = moderate effect",
    "- 0.60-0.79 = strong effect",
    "- 0.80-1.00 = very strong effect",
    "Omit advertisements for needs the interaction does not reasonably help. Do not normally generate 0.0.",
    "The advertisements property is required on every interaction, but its array may be empty only for support, control, maintenance, or refill interactions that contain at least one object-side effect.",
    "",
    "Generation rules:",
    "1. Generate appropriate physical or environmental objects for the location.",
    "2. Generate one or more meaningful interactions for each object.",
    "3. Prefer one interaction when one is enough.",
    "4. Add multiple interactions only when they represent genuinely different uses.",
    "5. Use complete need-satisfying interactions, not partial enabling steps.",
    "6. Attach advertisements to interactions, not directly to objects.",
    "7. Add a capacity object to every object.",
    "8. Add a duration object to every interaction.",
    "9. Add an availability object to every interaction.",
    "10. Use only capacity.type values limited or unlimited.",
    "11. Use only availability.type values always or when_capacity_available.",
    "12. Keep capacity and availability consistent.",
    "13. Add stateFlags and resources arrays to every object.",
    "14. Add requirements and effects arrays to every interaction.",
    "15. Use empty arrays when no state, stock, requirement, or effect is needed.",
    "16. Use only the exact need names supplied above.",
    "17. Assign weights according to how strongly the interaction satisfies the need.",
    "18. Consider relative strengths between interactions.",
    "19. Avoid assigning every weight the same value.",
    "20. Avoid assigning nearly every value close to 1.0.",
    "21. Do not generate advertisements with no reasonable relationship to the interaction.",
    "21a. Do not invent tiny advertisements for object-side controls, restoration, maintenance, or refill actions. Use an empty advertisements array when the interaction has a real object-side effect but no direct need-satisfaction value.",
    "22. Generate unique stable object IDs such as sofa_01.",
    "23. Generate stable interaction IDs such as sit_and_relax using lowercase letters, numbers, and underscores.",
    "24. Return only valid raw JSON.",
    "25. Follow the exact schema.",
    "26. Do not return any fields outside the schema.",
    "27. Do not generate runtime state engine, runtime resource engine, state mutation code, resource mutation code, occupancy, current users, available slots, claimed slots, reservations, queues, NPC inventory, NPC money, NPC permissions, NPC roles, NPC personalities, NPC need thresholds, time-of-day conditions, weather conditions, cross-object requirements, multi-object plans, navigation, pathfinding, animation, execution templates, Behavior Trees, action sequences, utility formulas, utility curves, arbitrary code, or simulator logic.",
    "",
    "Required JSON schema:",
    JSON.stringify(responseSchema, null, 2),
    "",
    "Return raw JSON only. Do not include Markdown, code fences, comments, or explanations."
  ].join("\n");
}

export function buildSmartObjectRepairPrompt({ invalidOutput, validationErrors, locationDescription, needs }) {
  const responseSchema = buildSmartObjectResponseSchema(needs);

  return [
    "Correct the invalid smart-object JSON output.",
    "Return corrected raw JSON only. Do not include Markdown, code fences, comments, or explanations.",
    "Objects must contain interactions, and interactions must contain advertisements. Do not put advertisements directly on objects.",
    "Every interaction must contain a duration object.",
    "Allowed duration types are instant, fixed, and continuous.",
    "Fixed durations require plausible real-world seconds greater than 0 and no greater than 86400.",
    "Instant and continuous durations must omit seconds.",
    "Use continuous when there is no predetermined stopping time. Use fixed when the interaction naturally completes. Use instant only when time is negligible.",
    "Every object must contain a capacity object.",
    "Capacity belongs to the object, is shared by all interactions, and counts simultaneous users of one object instance.",
    "Each generated object entry represents one object instance. Do not use slots to represent how many separate copies of an object exist.",
    "Allowed capacity types are limited and unlimited.",
    "Limited capacity requires integer slots from 1 to 100. Unlimited capacity must omit slots.",
    "Every object must contain stateFlags and resources arrays. Use empty arrays when no object-side state or finite stock is needed.",
    "Only approved state IDs are allowed: powered_on, operational, locked, open, clean.",
    "Every declared state must be referenced by at least one requirement on the same object. A set_state effect still must reference a declared state, but effect-only state references do not make that state useful.",
    "Do not create aftermath-only state. A declared state should affect at least one interaction requirement, and reusable blocking states should have a restoration interaction when appropriate.",
    "Only finite object-side stock should be resources. Every declared resource must be referenced by a requirement or effect on the same object.",
    "Every interaction must contain an availability object.",
    "Availability belongs to the interaction and must be an object with only a type field.",
    "Allowed availability types are always and when_capacity_available.",
    "Availability must match object capacity: limited capacity -> when_capacity_available; unlimited capacity -> always.",
    "Do not generate the old when_free availability value.",
    "Every interaction must contain requirements and effects arrays. Use empty arrays when no object-side requirement or effect is needed.",
    "Requirements and effects must reference declarations on the same parent object only.",
    "Every interaction must contain advertisements. The advertisements array may be empty only when the interaction contains at least one object-side effect, such as a control, restoration, maintenance, or refill action that does not directly satisfy a supplied need.",
    "Never invent tiny advertisements to fill the array. If there is no genuine need-satisfaction relationship and the interaction has a real object-side effect, use an empty advertisements array.",
    "Do not put need satisfaction into effects. Do not model capacity through requirements, resources, or effects.",
    "Do not create NPC-specific requirements, runtime state execution, runtime resource execution, arbitrary Boolean expressions, scripts, or code.",
    "Avoid over-modelling simple objects. Passive furniture should usually have empty stateFlags, resources, requirements, and effects.",
    "Guidance examples: single chair -> limited slots 1 -> when_capacity_available; single bed -> limited slots 1 -> when_capacity_available; toilet -> limited slots 1 -> when_capacity_available; shower -> limited slots 1 -> when_capacity_available; three-seat sofa -> limited slots 3 -> when_capacity_available; four-person dining table -> limited slots 4 -> when_capacity_available; public notice board -> unlimited -> always; radio -> unlimited -> always; shared television viewing -> unlimited -> always.",
    "Use complete need-satisfying interactions, not partial enabling steps.",
    "Generate support, control, maintenance, and refill interactions only when needed to keep declared state or finite resources coherent.",
    "Do not generate runtime occupancy data, current users, occupant IDs, claimed slots, remaining slots, reservations, queues, availability expressions, arbitrary Boolean logic, NPC stop conditions, NPC roles, NPC personalities, utility formulas, utility curves, arbitrary code, or simulator logic.",
    "",
    `Location description: ${locationDescription}`,
    "",
    "Allowed needs, definitions, and calibration references:",
    formatNeeds(needs),
    "",
    "Use the weak and strong calibration references to repair advertisement weights. The references are examples only; do not automatically generate reference objects. Per-need calibration takes priority over the generic scale: 0.01-0.19 minimal, 0.20-0.39 weak, 0.40-0.59 moderate, 0.60-0.79 strong, 0.80-1.00 very strong.",
    "",
    "Validation errors:",
    validationErrors.map((error) => `- ${error}`).join("\n"),
    "",
    "Required JSON schema:",
    JSON.stringify(responseSchema, null, 2),
    "",
    "Invalid output to repair:",
    invalidOutput
  ].join("\n");
}
